### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by arun81** [LasVegasCoder/Anti-DDOS-Script#2]
Hi Sir ,

Good Day !!!!

While Executing the below Script , getting the Syntax Error .

[root@localhost opt]# ./Simple-Anti-DDOS.sh
./Simple-Anti-DDOS.sh: line 7: syntax error near unexpected token `newline'
./Simple-Anti-DDOS.sh: line 7: `<!DOCTYPE html>'

Thanks

**Comment by MartinOfficial** [comment]
It also gives me the same error.

**Comment by LasVegasCoder** [comment]
This error is fixed, please report any other error. 

Thanks.

**Comment by MartinOfficial** [comment]
I still have this mistake
root@debian:~# wget https://github.com/LasVegasCoder/Anti-DDOS-Script/blob/master/advanced-anti-ddos.sh
--2019-11-03 15:13:08--  https://github.com/LasVegasCoder/Anti-DDOS-Script/blob/master/advanced-anti-ddos.sh
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘advanced-anti-ddos.sh’

advanced-anti-ddos.     [ <=>                  ]  92.84K  --.-KB/s   in 0.09s

2019-11-03 15:13:09 (1012 KB/s) - ‘advanced-anti-ddos.sh’ saved [95064]

root@debian:~# chmod +x advanced-anti-ddos.sh
root@debian:~# ./advanced-anti-ddos.sh
./advanced-anti-ddos.sh: line 7: syntax error near unexpected token `newline'
./advanced-anti-ddos.sh: line 7: `<!DOCTYPE html>'
